spring:
  application:
    name: ventas
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: IuqHqBidTpHJuINaboBzfMcqfczsqjJV
    hikari:
      data-source-properties:
        serverTimezone: America/Lima
  jackson:
    time-zone: America/Lima
  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
server:
  port: 8090
  servlet:
    context-path: /api
jwt:
  secret: dxvm7ucUwvwDslNrHOUZKHj17EA2dd5ujb9pqUgiXhg=
  expiration: '600000000'
